### ISSUE TITLE
First Android App codelab: 

### ISSUE THREAD

**Issue by RehabAbdAllah** [google-developer-training/first-android-app#10]
**Describe the problem**
A clear and concise description of what the problem is.
Troubleshooting: If you don't see the file fragment_first.xml, confirm you are running Android Studio 3.6 or later, which is required for this codelab.

The latest Andriod Studio IDE is 3.5.3 !
**In which step of the codelab can this issue be found?**
Step number.
4. Task: Explore the layout editor
**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

**codelab:** build-your-first-android-app-java

**Comment by xlr-8** [comment]
I ran into the same issue where the [official IDE is indeed 3.5.3](https://developer.android.com/studio/index.html#download), however when looking at [different channels](https://developer.android.com/studio/intro/update.html#channels) you can install versions up to 4.0.X - also available [here](https://developer.android.com/studio/preview/?utm_source=android-studio). Hope that helps

**Comment by GeneAndGoogle** [comment]
"Note: This version of the codelab requires Android Studio 3.6 or higher."
