### ISSUE TITLE
First Android app codelab: 

### ISSUE THREAD

**Issue by dgwingram** [google-developer-training/first-android-app#12]
**Describe the problem**
Text Alignment not showing in attributes

**In which step of the codelab can this issue be found?**
task 6 step 10 part 2
**Versions**
1. What version of Android Studio are you using?
_**Android Studio 3.6 RC 1
Build #AI-192.7142.36.36.6071332, built on December 13, 2019
Runtime version: 1.8.0_212-release-1586-b04 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1246M
Cores: 4
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: **_
2. What API level are you targeting?
targeting sdk 28, min SDK 16 (as per default)

**Additional information**
![AndroidIssueScreenshot](https://user-images.githubusercontent.com/41647671/71644668-61771000-2c9a-11ea-8f93-361c0cf78d9a.png)
![AndroidIssueScreenshot2](https://user-images.githubusercontent.com/41647671/71644669-61771000-2c9a-11ea-888c-811cb9777f26.png)
**codelab:** build-your-first-android-app-kotlin

**Comment by GeneAndGoogle** [comment]
Not sure why it went away, or when exactly it came back, but textAlignment is in Android Studio 3.6.3.
