### ISSUE TITLE
First Android app codelab: There is no fragment_first.xml

### ISSUE THREAD

**Issue by Structed** [google-developer-training/first-android-app#2]
**Describe the problem**
There is no `fragment_first.xml`

**In which step of the codelab can this issue be found?**
4. Task: Explore the layout editor
Step 1: Open the layout editor

**Versions**
1. Android Studio 3.5.2
2. Tried both with API Level 22 and 29
**codelab:** build-your-first-android-app-kotlin

**Comment by GeneAndGoogle** [comment]
As noted at the start of the codelab, this requires Android Studio 3.6 (which is in Beta; there's a [link](https://developer.android.com/studio/preview/) in the codelab).

**Comment by Structed** [comment]
🤦‍♂ sorry, as an experienced developer, I skipped the first few lines 😄 and I already had Android Studio installed via JetBrains Toolbox. Will try out the beta - thanks for the hint!

**Comment by GeneAndGoogle** [comment]
No worries. We're just deciding how to call out the requirement for AS3.6 better :-)

**Comment by Zwartfreak** [comment]
I am using Android studio 4.0 but still, the problem is same.
