### ISSUE TITLE
First Android app codelab: layout doesn't contain fragment_first.xml and fragment_second.xml files. But it should according to the tutorial.

### ISSUE THREAD

**Issue by electrino-dj** [google-developer-training/first-android-app#3]
**Describe the problem**
Description says: _"It also contains `content_main.xml`, `fragment_first.xml`, and `fragment_second.xml`."_ But there are no such files...

**In which step of the codelab can this issue be found?**
3

**Versions**
1. What version of Android Studio are you using?
3.5.2

2. What API level are you targeting?
29

**Additional information**
I'm a newbie, so maybe I'm missing something here. There are no steps describing how those files should appear in layout folder. Can I just add them?

**codelab:** build-your-first-android-app-kotlin

**Comment by GeneAndGoogle** [comment]
As noted at the start of the codelab, this requires Android Studio 3.6 (which is in Beta; there's a [link](https://developer.android.com/studio/preview/) in the codelab).

**Comment by Zwartfreak** [comment]
I am using Android studio 4.0 but still, the problem is same.
