### ISSUE TITLE
First Android app codelab: 

### ISSUE THREAD

**Issue by sneedle1** [google-developer-training/first-android-app#4]
I followed the tutorial and created a new Project and selected Basic Activity. In "4. Task: Explore the layout editor" the first thing to do is opening the fragment_first.xml. This file was not created in my project.

Android Studio 3.5.2
Build #AI-191.8026.42.35.5977832, built on October 30, 2019
JRE: 1.8.0_202-release-1483-b03 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Android API level 29

**Additional information**

**codelab:** build-your-first-android-app-kotlin

**Comment by GeneAndGoogle** [comment]
As noted in the intro and install instructions, this codelab requires Android Studio 3.6 or higher.

I have added another note at the step you mentioned:

> Troubleshooting: If you don't see the file fragment_first.xml, confirm you are running Android Studio 3.6 or later, which is required for this codelab.
