### ISSUE TITLE
First Android App codelab: 

### ISSUE THREAD

**Issue by Davepn16** [google-developer-training/first-android-app#47]
**Describe the problem**
import androidx.navigation.fragment.navArgs is missing a ;
Also, Android Studio couldn't find it, but it didn't need it either.

**In which step of the codelab can this issue be found?**
Step 8

**Versions**
1. What version of Android Studio are you using?
3.6.3, latest as of yesterday.
2. What API level are you targeting?
Whatever the default was.

**Additional information**
Not a biggie as it wasn't really required, but other noobs might get hung up on the issue.

Great tutorial otherwise!

**codelab:** build-your-first-android-app-java

**Comment by GeneAndGoogle** [comment]
Thanks for catching that. Spend most of my time with Kotlin these days...not missing the semicolons ;-)
