### ISSUE TITLE
First Android App codelab: 

### ISSUE THREAD

**Issue by kucukaslan** [google-developer-training/first-android-app#48]
**Describe the problem**
Double semicolon in the end of the line

**In which step of the codelab can this issue be found?**
Task 9, step 7, example(substep ?)  4 

> Create an action with currentCount as the argument to actionFirstFragmentToSecondFragment().

`FirstFragmentDirections.ActionFirstFragmentToSecondFragment action = FirstFragmentDirections.actionFirstFragmentToSecondFragment(currentCount);;`

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

**codelab:** build-your-first-android-app-java

**Comment by GeneAndGoogle** [comment]
Thanks for catching that. Over-compensating when switching back from Kotlin :-)
