### ISSUE TITLE
First Android App codelab: 

### ISSUE THREAD

**Issue by vas-dev-69** [google-developer-training/first-android-app#49]
Describe the problem
Incorrect path, "File > Other Settings > Preferences for New Projects" does not exist and should be: "File > Other Settings > Settings for New Projects".
Also the following route is incomplete ("Auto Imports") and should be "Other settings > Auto Import".

**In which step of the codelab can this issue be found?**
Build Your First Android App in Java, section 8.1.1 and 8.1.2.

**Versions**
1. Using Android Studio v3.6.3
2. What API level are you targeting? (Sorry, i am noob)

**Additional information**
Nothing, just enjoying the codelab.

**codelab:** build-your-first-android-app-java

**Comment by GeneAndGoogle** [comment]
Thanks for the feedback.

Are you sure about the version of Android Studio? I see "Preferences for New Projects" in 3.6.3. I think it may have been "Settings" in older versions of Android Studio.

![Screen Shot 2020-05-07 at 11 40 58 AM](https://user-images.githubusercontent.com/54457695/81332328-c8953e80-9057-11ea-8b88-d7340fb02577.png)

**Comment by SplitUranium** [comment]
My 3.6.3 is showing "Settings for New Projects..." where yours has "Preferences for New Projects...", @GeneAndGoogle

**Comment by vas-dev-69** [comment]
I guess its a difference between ios and windows (version 3.6.3, build from april 14, 2020.
![image](https://user-images.githubusercontent.com/64542460/82129746-2a2a7b00-97c5-11ea-9cc0-147b3bc77ab3.png)

**Comment by GeneAndGoogle** [comment]
Strange. And I believe it's going to change again a bit in Android Studio 4.0.
