### ISSUE TITLE
First Android app codelab: 

### ISSUE THREAD

**Issue by audiophyl** [google-developer-training/first-android-app#5]
**Describe the problem**
Instructions are incorrect, at least for the android-studio-preview snap (v. 3.6 Canary 9). Zoom controls are not in the lower right, they are in the upper right. The graphical representation depicted is also not correct.

**In which step of the codelab can this issue be found?**
In #4 (Task: Explore the layout editor), Step 1, Instruction 5: "At the lower right of the Design editor you see + and - buttons for zooming in and out. Use these buttons to adjust the size of what you see, or click the zoom-to-fit button so that both panels fit on your screen."

**Versions**
1. What version of Android Studio are you using? 3.6 Canary 9
2. What API level are you targeting? 27

**Additional information**

**codelab:** build-your-first-android-app-kotlin

**Comment by GeneAndGoogle** [comment]
They're in the lower right in AS 3.6 Beta 4. If they move them again, we'll update the codelab.
