### ISSUE TITLE
First Android app codelab: 

### ISSUE THREAD

**Issue by reknoZ** [google-developer-training/first-android-app#6]
**Describe the problem**
Step 10. Item 2: There is no textAlignment in the Attributes section. I can't find it using the filter. I can't find it by showing AllAttributes and scrolling through. I've searched for "text" and "alignment". It's not there. 

**In which step of the codelab can this issue be found?**
Step 10

**Versions**
1. What version of Android Studio are you using? 3.6 beta 5
2. What API level are you targeting? 29

**Additional information**

**codelab:** build-your-first-android-app-kotlin

<img width="285" alt="Capture d’écran 2019-12-15 à 12 03 47" src="https://user-images.githubusercontent.com/2046283/70861771-05d72380-1f33-11ea-980c-31edf7e215ad.png">
<img width="278" alt="Capture d’écran 2019-12-15 à 12 03 55" src="https://user-images.githubusercontent.com/2046283/70861774-08397d80-1f33-11ea-977f-d689dbd9e92c.png">

**Comment by GeneAndGoogle** [comment]
Interesting... I wonder when and why that disappeared. You can still add the property manually in XML, but definitely gone from the Attributes panel. I've sent a inquiry.

**Comment by GeneAndGoogle** [comment]
Not sure why it went away, or when exactly it came back, but textAlignment is in Android Studio 3.6.3.
