### ISSUE TITLE
Tasks 9 of 10, Step 7: Update SecondFragment to compute and display a random number

### ISSUE THREAD

**Issue by bass212drum** [google-developer-training/first-android-app#81]
**In which step of the codelab can this issue be found?**
Tasks 9 of 10, Step 7: Update SecondFragment to compute and display a random number
     In SecondFragment.kt,  to add     ---      val count = args.myArg
**Versions**
    What version of Android Studio are you using? android 4.1.1
    What API level are you targeting? API level 22

**Additional information**
codelab: build-your-first-android-app-java

**Comment by vbaco87** [comment]
did you manage to find a solution? i'm also stuck there

**Comment by bass212drum** [comment]
I solved that problem, but I kind of forgot about how did I solve it. I
probably left a note of how did I solve it.

**Comment by vbaco87** [comment]
I solved it just by rebooting the device 
Thanks for replyin :)

**Comment by bass212drum** [comment]
Awesome, Good for you !
