### ISSUE TITLE
First Android app codelab: 

### ISSUE THREAD

**Issue by dishiinboxru** [google-developer-training/first-android-app#9]
**Describe the problem**
the guide requires 3.6 version of android studio, while latest stable one is 3.5. 

**In which step of the codelab can this issue be found?**
welcome

**Versions**
1. What version of Android Studio are you using? 3.5

**codelab:** build-your-first-android-app-kotlin

**Comment by GeneAndGoogle** [comment]
As noted, "Note: This version of the codelab requires Android Studio 3.6 or higher."
